---
title: "The Effects of Supply on Medical Labor Markets"
subtitle: "Evidence from Dental School Closures in Finland"
author: 
   - name: Mikko Herzig
     affiliation: University of Turku, Finnish Institute for Health and Welfare Finnish Ministry of Finance
   - name: Konsta Lavaste
     affiliation: Finnish Institute for Health and Welfare
   - name: Allan Seuri
     affiliation: Tampere University, Ministry of Finance
date: today
date-format: long
lang: "en-US"
format:
   html:
      keep_md: true
      code-fold: show
      toc: false
editor: visual
license: MIT
keywords: ["labor supply", "universities", "dental schools", "healthcare", "physician", "earnings"]
---

## Preliminaries

First, let's load the setup and functions into memory.

```{r}
#| label: preliminaries
#| echo: true
#| output: false

# Load knitr
  library(knitr)

# Load here package for relative file paths
  library(here)

# Run setup script
  source(here("scripts", "00_setup.R"))

# Load functions
  source(here("scripts", "00_functions.R"))

```

## Map

In this section we create map of Finland which includes:
1. locations of dental schools
2. commuting zones

```{r}
#| label: map
#| echo: true
#| output: true

# Which year's commuting zones we want to use
  commutingzones_year <- 2019

# Run the script
  source(here("scripts", "01_map.R"))

```















